import type { NextPage } from 'next'
import Head from 'next/head'
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import Grid from '@mui/material/Grid';
import { getComics } from 'dh-marvel/services/marvel/marvel.service';
import { GetServerSideProps } from "next";
import { Comics } from "../interface/character"
import { useState } from 'react';
import { ComicCard } from 'dh-marvel/components/ui/comicCard';
import { LoadMore } from 'dh-marvel/components/load-more';


interface Props {
    comics: Comics[];
}



const Index: NextPage<Props> = ({ comics }) => {
    const [loadedComics, setLoadedComics] = useState<Comics[]>(comics || []);
    // console.log('loadedComics', loadedComics)

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <BodySingle title={"Sample"}>
                <Grid container spacing={2}>
                    <ComicCard comicsArr={loadedComics} />
                    <LoadMore />
                </Grid>

            </BodySingle>
        </>
    )
}

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
    const comics = await getComics(1, 12);

    res.setHeader(
        'Cache-Control',
        'public, s-maxage=10, stale-while-revalidate'
    )


    return {
        props: {
            comics: comics.data.results
        },
    };
};

export default Index
